---
title: "Articles to be Followed"
output: html_notebook
---

- Are Pathologists Biased? Effect of Blinding on Pathologist Assessment of Lymph-Vascular Invasion in Breast Cancer (Proposal for New Generation Internet-Based Randomized Controlled Trial Design)

https://www.researchgate.net/publication/269349949_Are_Pathologists_Biased_Effect_of_Blinding_on_Pathologist_Assessment_of_Lymph-Vascular_Invasion_in_Breast_Cancer_Proposal_for_New_Generation_Internet-Based_Randomized_Controlled_Trial_Design

- Research Myles

https://www.researchgate.net/publication/279942179_Research_Myles

- Breast Pathology Overview for Undergraduate Medical Students and Technologists

https://www.researchgate.net/publication/282032279_Breast_Pathology_Overview_for_Undergraduate_Medical_Students_and_Technologists

- Breast Surgical PAthology: Not So Routine Cases

https://www.researchgate.net/publication/282033353_Breast_Surgical_PAthology_Not_So_Routine_Cases

- Statistics For Pathologists Primer • Focus on Diagnostic Accuracy

https://www.researchgate.net/publication/326283666_Statistics_For_Pathologists_Primer_Focus_on_Diagnostic_Accuracy

- Canadian Association of Pathologists Statistics for Pathologists Primer: Focus on Diagnostic Accuracy Statistics Workshop Task1 How To Analyze Accuracy of a Binary Test

https://www.researchgate.net/publication/326284820_Canadian_Association_of_Pathologists_Statistics_for_Pathologists_Primer_Focus_on_Diagnostic_Accuracy_Statistics_Workshop_Task1_How_To_Analyze_Accuracy_of_a_Binary_Test

- Biomarkers: Evidence we have and Evidence we need

https://www.researchgate.net/publication/326278738_Biomarkers_Evidence_we_have_and_Evidence_we_need

- Canadian Association of Pathologists Statistics for Pathologists Primer: Focus on Diagnostic Accuracy Statistics TASK 2 MULTILEVEL TEST Workshop

https://www.researchgate.net/publication/326286944_Canadian_Association_of_Pathologists_Statistics_for_Pathologists_Primer_Focus_on_Diagnostic_Accuracy_Statistics_TASK_2_MULTILEVEL_TEST_Workshop

- Canadian Association of Pathologists Statistics for Pathologists Primer: Focus on Diagnostic Accuracy Statistics Task 3 Measuring Agreement Workshop

https://www.researchgate.net/publication/326286968_Canadian_Association_of_Pathologists_Statistics_for_Pathologists_Primer_Focus_on_Diagnostic_Accuracy_Statistics_Task_3_Measuring_Agreement_Workshop

Impact of MSC in Evidence based Healthcare
http://www.cebm.net/impact-msc-evidence-based-health-care/
https://www.researchgate.net/publication/263194216_Impact_of_MSC_in_Evidence_based_Healthcare_httpwwwcebmnetimpact-msc-evidence-based-health-care

- Analytical Approach to Quality Control In Diagnostic Immunohistochemistry

https://www.researchgate.net/publication/282032540_Analytical_Approach_to_Quality_Control_In_Diagnostic_Immunohistochemistry

- Modelling Canadian quality control test program for steroid hormone receptors in breast cancer using hierarchical modelling: Diagnostic accuracy study

https://www.researchgate.net/publication/296070802_Modelling_Canadian_quality_control_test_program_for_steroid_hormone_receptors_in_breast_cancer_using_hierarchical_modelling_Diagnostic_accuracy_study

- Why we Need Evidence-Based Breast Cancer Biomarker Testing?

https://www.researchgate.net/publication/267328532_Why_we_Need_Evidence-Based_Breast_Cancer_Biomarker_Testing


- The Inevitable Math behind Entitlement Reform

https://www.nejm.org/doi/full/10.1056/NEJMp1801807?query=TOC

- Twitter Tailwinds — Little Capsules of Gratitude

https://www.nejm.org/doi/full/10.1056/NEJMp1806737?query=TOC

- C-kit (CD117) immunostain is useful for the diagnosis of Giardia lamblia in duodenal biopsies

https://www.humanpathol.com/article/S0046-8177(08)00358-4/fulltext

- desquamative interstitial pneumonia

https://twitter.com/smlungpathguy/status/1018703292283711488

- cornellpathology

https://www.youtube.com/user/cornellpathology/playlists


- Statistical Methods in Integrative Genomics

https://www.annualreviews.org/doi/10.1146/annurev-statistics-041715-033506

- Big Data Approaches for Modeling Response and Resistance to Cancer Drugs

https://www.annualreviews.org/doi/10.1146/annurev-biodatasci-080917-013350

-

https://margrietpalm.github.io/SMB2018/#/

- Comedonecrosis Revisited: Strong Association With Intraductal Carcinoma of the Prostate.

https://www.ncbi.nlm.nih.gov/pubmed/29878934?dopt=Abstract

- Physics of living systems 
 
https://www.nature.com/collections/jwxbtzdjkh
 
- Using Bayesian Methods in Business and Marketing
 
https://www.jmp.com/en_us/events/ondemand/analytically-speaking/using-bayesian-methods-in-business-and-marketing.html?utm_campaign=td7011O000002OuZY&utm_source=jmpblog&utm_medium=social

