# Media upload

## PBPath Journal Watch August September 2018

http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.pdf

Journal Watch August September 2018

<strong>Journal Watch August September 2018</strong>

<a href="http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.pdf">Click here to download pdf</a>


<iframe src="http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.pdf" style="width: 100%; height: 400px; border: none;"></iframe>


## Pancreatobiliary Pathology Society Journal Watch August September 2018

http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.html

Pancreatobiliary Pathology Society Journal Watch August September 2018

Pancreatobiliary Pathology Society Journal Watch August September 2018

---

# /journal-watch


<p>If you are not directed to the most recent Journal Watch then click <a href="http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.html"><strong>here</strong></a></p>


```
<!-- 

<p>Pancreatobiliary Pathology Society Journal Watch August September 2018 is being prepared. Subscribe to the newsletter <a href="http://pbpath.org/newsletter/" target="_blank" rel="noopener"><strong>here</strong></a> and stay tuned.</p>

 -->
```

---

# /journal-watch-archive



<p><strong>Pancreatobiliary Pathology Society Journal Watch</strong></p>
<p>To see previous issues, please click on the links below</p>
<ul>
	<li><a href="http://pbpath.org/pbpath-journal-watch-june-july-2018/"><strong>June-July 2018</strong></a></li>
	<li><a href="http://pbpath.org/pbpath-journal-watch-august-september-2018/"><strong>August-September 2018</strong></a></li>
</ul>


---


# /journal-watch-upcoming-issue/ 


<p><strong>Pancreatobiliary Pathology Society Journal Watch</strong><br />
<strong>Below is the unofficial (draft) version of the upcoming issue. <br />
See the current version by <a href="http://pbpath.org/journal-watch/"><em>clicking here</em></a>.</strong></p>
<p><iframe src="https://sbalci.github.io/JournalWatchPBPath/PBPath-Journal-Watch-October-November-2018.nb.html" name="frame1" width="100%" height="800px" frameborder="no" scrolling="auto" align="center"></iframe></p>

---

# Tools --> Redirect

/journal-watch/

http://pbpath.org/wp-content/uploads/2018/10/PBPath-Journal-Watch-August-September-2018.html

---


