---
title: "Meeting Abstracts"
output: html_notebook
---


# Meeting Abstracts

- **ECP 2018**  
30th European Congress of Pathology  
Virchows Archiv Volume 473, Issue 1 Supplement, September 2018  
https://link.springer.com/article/10.1007/s00428-018-2422-1  
https://doi.org/10.1007/s00428-018-2422-1  



---

- **American Pancreatic Association Annual Meeting Abstracts**

https://journals.lww.com/pancreasjournal/Pages/annualmeetingabstracts.aspx


---

- **Abstract of the 13th World Congress of the International Hepato-Pancreato-Biliary Association, 4-7 September 2018, Geneva, Switzerland**

https://www.hpbonline.org/issue/S1365-182X(18)X0010-0

---

- **Validation of AJCC 8th edition pancreatic cancer staging system using a large multinational data**

https://www.hpbonline.org/article/S1365-182X(18)33391-4/fulltext

---

- **Is the new T1 category defined by the 8th edition AJCC pancreatic cancer staging system an improvement? An evaluation by multinational data**

https://www.hpbonline.org/article/S1365-182X(18)33395-1/fulltext

---


- **Abstracts of Papers Submitted to the 49th Annual Meeting of the American Pancreatic Association, October 31-November 3, 2018, Miami Beach, Florida.**


https://www.ncbi.nlm.nih.gov/pubmed/30383711


---


- **International validation of the 8th edition American joint committee on cancer (AJCC) TNM staging system in patients with resected pancreatic cancer**


https://www.hpbonline.org/article/S1365-182X(18)33748-1/fulltext


---

<a href="#top">Back to top</a>

\pagebreak
