
## Excluded Ampulla {#ampulla}




---

```{r ampulla 32773194, include=FALSE}

PMID_32773194 <- RefManageR::ReadPubMed('32773194', database = 'PubMed')

citation_32773194 <- paste0(PMID_32773194$journal,' ', PMID_32773194$year, ' ', PMID_32773194$month,';', PMID_32773194$volume,'(', PMID_32773194$number,'):', PMID_32773194$pages)

PubMed_32773194 <- paste0(PubMedString, PMID_32773194$eprint)

doi_32773194 <- paste0(doiString, PMID_32773194$doi)

Sys.sleep(2)

```

<details open> <summary>
- **`r PMID_32773194$title`**
</summary> 

*`r citation_32773194`*

`r PubMed_32773194`

`r PMID_32773194$abstract`

`r doi_32773194`

</details>

---




---

```{r ampulla 32171280, include=FALSE}

PMID_32171280 <- RefManageR::ReadPubMed('32171280', database = 'PubMed')

citation_32171280 <- paste0(PMID_32171280$journal,' ', PMID_32171280$year, ' ', PMID_32171280$month,';', PMID_32171280$volume,'(', PMID_32171280$number,'):', PMID_32171280$pages)

PubMed_32171280 <- paste0(PubMedString, PMID_32171280$eprint)

doi_32171280 <- paste0(doiString, PMID_32171280$doi)

Sys.sleep(2)

```

<details open> <summary>
- **`r PMID_32171280$title`**
</summary> 

*`r citation_32171280`*

`r PubMed_32171280`

`r PMID_32171280$abstract`

`r doi_32171280`

</details>

---








---

<a href="#top" target="_self">Back to top</a>

---

\pagebreak

