

---

```{r ampulla NA, include=FALSE}

PMID_NA <- RefManageR::ReadPubMed('NA', database = 'PubMed')

citation_NA <- paste0(PMID_NA$journal,' ', PMID_NA$year, ' ', PMID_NA$month,';', PMID_NA$volume,'(', PMID_NA$number,'):', PMID_NA$pages)

PubMed_NA <- paste0(PubMedString, PMID_NA$eprint)

doi_NA <- paste0(doiString, PMID_NA$doi)

dimensionBadge_NA <- paste0(dimensionString1, PMID_NA$doi,dimensionString2)

altmetricBadge_NA <- paste0(altmetricString1, PMID_NA$doi, altmetricString2 )

Sys.sleep(2)

```

<details open> <summary>
- **`r PMID_NA$title`**
</summary> 

*`r citation_NA`*

`r PubMed_NA`

`r PMID_NA$abstract`

`r doi_NA`

`r dimensionBadge_NA`

`r altmetricBadge_NA`

</details>

---




---

```{r ampulla , include=FALSE}

PMID_ <- RefManageR::ReadPubMed('', database = 'PubMed')

citation_ <- paste0(PMID_$journal,' ', PMID_$year, ' ', PMID_$month,';', PMID_$volume,'(', PMID_$number,'):', PMID_$pages)

PubMed_ <- paste0(PubMedString, PMID_$eprint)

doi_ <- paste0(doiString, PMID_$doi)

dimensionBadge_ <- paste0(dimensionString1, PMID_$doi,dimensionString2)

altmetricBadge_ <- paste0(altmetricString1, PMID_$doi, altmetricString2 )

Sys.sleep(2)

```

<details open> <summary>
- **`r PMID_$title`**
</summary> 

*`r citation_`*

`r PubMed_`

`r PMID_$abstract`

`r doi_`

`r dimensionBadge_`

`r altmetricBadge_`

</details>

---


